//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public int clientID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string phoneNo { get; set; }
        public string Sex { get; set; }
        public string planType { get; set; }
    }
}
