//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientMembership
    {
        public int ID { get; set; }
        public int clientID { get; set; }
        public int planID { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
    
        public virtual tblClient tblClient { get; set; }
        public virtual tblPlan tblPlan { get; set; }
    }
}
