//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlan()
        {
            this.tblClientMemberships = new HashSet<tblClientMembership>();
        }
    
        public int planID { get; set; }
        public string planName { get; set; }
        public string planDescription { get; set; }
        public string planTerm { get; set; }
        public int planPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientMembership> tblClientMemberships { get; set; }
    }
}
