//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlan
    {
        public int planID { get; set; }
        public string planName { get; set; }
        public string planDescription { get; set; }
        public string planTerm { get; set; }
        public int planPrice { get; set; }
    }
}
