//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public int userSecurityLevel { get; set; }
        public string userFullname { get; set; }
    
        public virtual tblSecurityLevel tblSecurityLevel { get; set; }
    }
}
